version: "3.3"

services:
  # Dynamic DNS configuration
  cloudflare-ddns:
      image: oznu/cloudflare-ddns:latest
      restart: always
      environment:
        - API_KEY=${CF_API_KEY}
        - ZONE=${CF_ZONE}
        - SUBDOMAIN=${CF_SUBDOMAIN}

  # Load Balancing for internal services
  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      # Docker Provider
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # Traefik Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=true"
      # Secure Entrypoint
      - "--entrypoints.websecure.address=:443"
      # TLS - Wildcard
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.email=${EMAIL}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=letsencrypt"
      - "--entrypoints.websecure.http.tls.domains[0].main=${CF_ZONE}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${CF_ZONE}"
      # Log access
      - "--accesslog=true"
    environment:
      - CLOUDFLARE_EMAIL=${EMAIL}
      - CLOUDFLARE_DNS_API_TOKEN=${CF_API_KEY}
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # Test Service
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`jarvis.simonduff.net`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"

  # BusyBox, just for testing
  bb:
    image: "busybox"
    container_name: "busybox"
    tty: true
    labels:
      - "traefik.enable=false"

  # MQTT Broker
  mqtt:
    image: "hivemq/hivemq4"
    container_name: "mqtt-broker"
    labels:
      - "traefik.enable=false"
    ports:
      - "1883:1883"
      - "8883:8080"
